if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    if(DEFINED ENV{MSVCDIR})
        set(MSVCDIR $ENV{MSVCDIR})
        add_library(cxxmodules STATIC "${MSVCDIR}/modules/std.ixx")
        target_compile_options(cxxmodules PUBLIC /std:c++latest)
    else()
        message(FATAL_ERROR "Environment variable MSVCDIR is not defined.")
    endif()
endif()
